// <auto-generated/>
using Microsoft.AspNetCore.Components;

namespace PageComponents.Components;

public partial class BaseSection
{
    /// <summary>
    /// Content der Section
    /// </summary>
    [Parameter]
    public RenderFragment? ChildContent { get; set; }

    /// <summary>
    /// Zusätzliche CSS-Klassen
    /// </summary>
    [Parameter]
    public string? CssClass { get; set; }
}