// <auto-generated/>
using Microsoft.AspNetCore.Components;

namespace PageComponents.Components;

public partial class TelegramLink
{
    [Parameter]
    public string Username { get; set; } = "";

    [Parameter]
    public string DisplayName { get; set; } = "";

    [Parameter]
    public RenderFragment? ChildContent { get; set; }
}